# Плагин принадлежит студии KleksyStudio - vk.com/kleksystudio
# Данный плагин защищён апвторским правом!
# Любые изменения, доработки категорически запрещены без разрешения автора плагина - KleksyStudio
#
# Настройки прав и наличии "библиотек-плагинов" отсутствует.
# Сообщения
messages:
  noPermission: '&c&lMINE&f&lSIDE&8&l: &fУ вас &cнедостаточно &fправ'
  noPlayer: '&c&lMINE&f&lSIDE&8&l: &fИгрок не найден!'
  usePlayers: '&c&lMINE&f&lSIDE&8&l: &fТолько для игроков!'
  rtp:
    safe: '&c&lРТП: &fВы были телепортироаны на координаты &a$x&f, &a$y&f, &a$z' # Переменные места телепортации: $x - Координата x, $y - Координата y, $z - Координата z, $world - Мир
    pvp: '&c&lРТП: &fВы были телепортироаны на координаты &a$x&f, &a$y&f, &a$z&f. Игроков поблизости: &a$nearPlayers' # Переменные места телепортации: $x - Координата x, $y - Координата y, $z - Координата z, $world - Мир, $nearPlayers - Игроков поблизости
    online: '&c&lРТП: &fВы один!'
  leave:
    usage: '&c&lMINE&f&lSIDE&8&l: &fИспользуйте &e/leave <Ник игрока>'
    gived: '&c&lMINE&f&lSIDE&8&l: &fИгроку &e$target &fбыло выдано перо телепортации'
  log:
    usage:
    - ''
    - '&c&lИНФОРМАЦИЯ: &cИспользуйте: &f/log off/on'
    - ''
    enable: '&c&lИНФОРМАЦИЯ: &fЛоги были &aвключены&f!'
    enableAlready: '&c&lИНФОРМАЦИЯ: &fЛоги уже были &aвключены&f!'
    disable: '&c&lИНФОРМАЦИЯ: &fЛоги были &cвыключены&f!'
    disableAlready: '&c&lИНФОРМАЦИЯ: &fЛоги уже были &cвыключены&f!'
    log: '&c&lЛОГИ: &e$player &fиспользовал команду: &c$cmd'
  ping: '&c&lMINE&f&lSIDE&8&l: &fВаш пинг на сервере &e&l$ping'
  warps:
    case:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nкейсам&f, удачной игры!'
      - '&8╚ '
    mine:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nШахте&f, удачной игры!'
      - '&8╚ '
    portals:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nПорталам&f, удачной игры!'
      - '&8╚ '
    pvp:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nПвП-Арене&f, удачной игры!'
      - '&8╚ '
    shops:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nМагазинам&f, удачной игры!'
      - '&8╚ '
    tops:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nТопам сервера&f, удачной игры!'
      - '&8╚ '
    wood:
      - '&8╔'
      - '&8║ &fВы успешно телепортированы'
      - '&8║ &fК &c&nЛесорубке&f, удачной игры!'
      - '&8╚ '
settings:
  join: true # Скрыть сообщение при заходе игрока
  quit: true # Скрыть сообщение при выходе игрока
  death: true # Скрыть сообщение при смерти игрока
  advancements: true # Скрыть показ ачивок
  pistons: true # Отключить баг с приватами WorldGuard при сдвиге поршней
  worlds:
    spawn: 'spawn'
    game: 'world' # $worldPlayer - Мир где находится игрок
  perms:
    leave: 'kleksystudio.leave'
    rtp: 'kleksystudio.rtp.pvp'
  rtp:
    coords: 5000
    world: 'world'